CREATE TABLE IF NOT EXISTS strategy_catalog (
 id SERIAL PRIMARY KEY,
 strategy_name TEXT NOT NULL,
 ticker TEXT NOT NULL,
 version TEXT NOT NULL DEFAULT '1.0',
 author TEXT NOT NULL DEFAULT 'human',
 source TEXT NOT NULL DEFAULT 'manual',
 status TEXT NOT NULL DEFAULT 'candidate',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 last_walkforward TIMESTAMPTZ,
 last_replay TIMESTAMPTZ,
 walkforward_verdict TEXT,
 replay_trades INTEGER DEFAULT 0,
 replay_win_rate DOUBLE PRECISION,
 replay_profit_factor DOUBLE PRECISION,
 replay_expectancy DOUBLE PRECISION,
 replay_total_pnl DOUBLE PRECISION,
 replay_max_drawdown DOUBLE PRECISION,
 replay_sharpe DOUBLE PRECISION,
 replay_sortino DOUBLE PRECISION,
 meta_score DOUBLE PRECISION DEFAULT 0,
 priority INTEGER DEFAULT 0,
 notes TEXT,
 UNIQUE(strategy_name, ticker, version)
);
