ALTER TABLE paper_positions
ADD COLUMN IF NOT EXISTS exit_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS exit_price NUMERIC,
ADD COLUMN IF NOT EXISTS pnl NUMERIC,
ADD COLUMN IF NOT EXISTS pnl_pct NUMERIC;

ALTER TABLE paper_positions
ADD COLUMN IF NOT EXISTS close_reason TEXT;